connectbot/connectbot

src/org/connectbot/PubkeyListActivity.java
The PubkeyListActivity lifecycle and the ServiceConnection lifecycle are independent. In the case that the `onCreateContextMenu` callback fires before the `onServiceConnected callback`, the `bound` field will be null in onCreateContextMenu (as well as in some of its callees and in the callbacks that it registers) and can throw an exception when dereferenced. This pull request fixes the issue by including a check that `bound` is non-null when computing the `loaded` boolean that guards the potentially failing dereferences of `bound`.
=> Fixing possible NPE in PubkeyListActivity

src/org/connectbot/HostListActivity.java
The HostListActivity lifecycle and the ServiceConnection lifecycle are independent. In the case that the `onCreateContextMenu` callback fires before the `onServiceConnected` callback, the `bound` field will be null in `onCreateContextMenu` and can throw an exception. This pull request fixes the issue by checking for `bound` for null before dereferencing it.
=> Fix possible NPE in HostListActivity.onCreateContextMenu

src/org/connectbot/service/TerminalManager.java
Patch for Issue 388.
Disconnect all connection if onDestroy called, but disconnect connections which use network if onConnectivityLost called.
=> Keep local connections when network down.

res/layout/act_hostlist.xml
This fixes a bug in landscape where the input is not visible at all.
See
http://stackoverflow.com/questions/23982098/android-relativelayout-layout-above-appears-to-behave-incorrectly-with-layout-a.
=> Switch the quick connect entry in the hostlist to a LinearLayout.

app/src/main/java/org/connectbot/ConsoleActivity.java
This bug was due to an error is findCurrentView() since it was
looking in the TerminalView rather than its wrapper.
=> Ensure that console title overlays are shown when switching views.

app/src/main/res/values/notrans.xml, app/src/main/res/values/strings.xml
This relieves some need for translations to many languages.
=> Use unicode symbols for arrow buttons

app/src/main/java/org/connectbot/ConsoleActivity.java
This fixes an issue where the tab indicator was disappearing when the
device was rotated. It also avoids a total crash when updating to 22.2.1
design support libraries.
=> TabLayout.setupWithViewPager is broken. Implement a fixed version.

app/src/main/java/org/connectbot/ConsoleActivity.java
It seems in ConsoleActivity.onTerminalChanged() is sometime called before the view has actually changed so adapter.getCurrentTerminalView() does not always return the actual TerminalView but sometimes returns the one selected just before, so setTitle() was setting the wrong title. Also it returns null in some cases so the title was not set at all.
=> Activity title not sync correctly with ViewPager

.travis.yml, scripts/check-lint-count.sh
I'm always lost with new lint issues... so the idea here is to store the last good lint results and to compare it with the new one, and show the diff if count is higher.
=> Try to show new lint issues in check-lint-count.sh

app/src/main/res/values-v11/styles.xml
There is some kind of problem with inheriting TextAppearance.AppCompat
on API 10 and before that causes a crash. Instead only inherit it on API
11 (Honeycomb) and later. This doesn't make any visual difference with
Gingerbread and before.
=> Fix host list for API 10 and before

app/src/androidTest/java/org/connectbot/StartupTest.java, app/src/main/java/org/connectbot/ColorsActivity.java, app/src/main/java/org/connectbot/ConsoleActivity.java, app/src/main/java/org/connectbot/GeneratePubkeyActivity.java, app/src/main/java/org/connectbot/HostEditorActivity.java, app/src/main/java/org/connectbot/HostListActivity.java, app/src/main/java/org/connectbot/PortForwardListActivity.java, app/src/main/java/org/connectbot/PubkeyListActivity.java, app/src/main/java/org/connectbot/data/ColorStorage.java, app/src/main/java/org/connectbot/data/HostStorage.java, app/src/main/java/org/connectbot/service/BackupAgent.java, app/src/main/java/org/connectbot/service/TerminalBridge.java, app/src/main/java/org/connectbot/service/TerminalManager.java, app/src/main/java/org/connectbot/transport/SSH.java, app/src/main/java/org/connectbot/transport/TransportFactory.java, app/src/main/java/org/connectbot/util/Colors.java, app/src/main/java/org/connectbot/util/HostDatabase.java, app/src/main/java/org/connectbot/util/PubkeyDatabase.java
Totally refactor the way databases work. The current advice is to never close the database when using a `SQLiteOpenHelper` and to use transactions when writing to the database. The old system of using locks around use of database kind of worked, but there were places that were violating this principle.
This is the first step toward using something like SQLBrite which will allow us to use a more reactive style for updating the host list, et al.
=> Database refactor

app/build.gradle, app/src/main/java/org/connectbot/HostListActivity.java, app/src/main/res/layout/act_hostlist.xml, app/src/main/res/layout/item_host.xml, app/src/main/res/values-v11/styles.xml, app/src/main/res/values/styles.xml
This converts the rest of the view to the Material Design spec. Changes include item animation as well as the "shadow" semicircles which appear at the top and bottom of the list when scrolling. Furthermore, performance should be improved through automatic view recycling.
Note that the click handler and context menu handler were only moved and were left unchanged. RecyclerView use requires that these handlers are applied to the individual child views instead of being added to the list ViewGroup as a whole.
=> Host list: convert to RecyclerView.

app/build.gradle, app/src/androidTest/java/org/connectbot/ConnectbotMatchers.java, app/src/androidTest/java/org/connectbot/StartupTest.java, app/src/main/java/org/connectbot/HostListActivity.java
The tests were broken after I converted from ListView to ReyclerView. There is still one issue left: localConnectionDisconnectConsoleActivity() still fails, and, ironically, it is the only test that did not need to be modified. @kruton, would you mind taking a look at this for me? Thanks.
=> Fix StartupTest tests to work with RecyclerView.

.idea/codeStyleSettings.xml
This makes lines shorter and easier to read.
=> Use 4 spaces per tab instead of 8.

app/src/main/res/layout/act_hostlist.xml
=> Add padding to bottom of HostList to prevent FAB covering list.

.travis.yml
If we try to test during the coverity scan, we get strange errors from
the build system. Also, it seems to pollute the next non-coverity
build, so make sure Travis cleans before trying to build again.
=> Make sure we clean after the coverity run

app/src/main/java/org/connectbot/HostListActivity.java, app/src/main/java/org/connectbot/PubkeyListActivity.java
Since we null check the host, we should make sure not to dereference it
later on.
=> Only use host if it is not null

app/src/main/java/org/connectbot/GeneratePubkeyActivity.java
Fixes #249.
This is a better solution than my previous PR, #250, because disabled buttons will remain grey.
=> Change getColor call that crashes on pre-APIv14

.idea/codeStyleSettings.xml
This converts XML such as:
&lt;Foo
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;attribute1="hi"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;attribute2="bye"&gt;
to:
&lt;Foo
&nbsp;&nbsp;&nbsp;&nbsp;attribute1="hi"
&nbsp;&nbsp;&nbsp;&nbsp;attribute2="bye"&gt;
=> Change "continuation indent" tab to only 4 spaces for XML.

app/src/main/res/values/strings.xml
=> Remove the reference to trackball from the bumpy arrows description.

app/src/main/java/de/mud/terminal/VDUInput.java, app/src/main/java/de/mud/terminal/vt320.java, app/src/main/java/org/connectbot/ConsoleActivity.java, app/src/main/java/org/connectbot/TerminalView.java
Only handle mouse events locally if shift is held.
Partially fixes #225. Still need to figure out mouse wheel forwarding
and proper copy support when the terminal is handling selection itself
(ie in an editor).
=> Forward mouseevents to the terminal when appropriate.

app/src/main/java/org/connectbot/HostEditorFragment.java, app/src/main/res/layout/fragment_host_editor.xml, app/src/main/res/values/strings.xml
This PR adds all the remaining UI fields and hooks them up to the fragment's HostBean object.
Remaining work includes:
1) Passing in initial data to the fragment if it exists.
2) Saving the host after it has been edited.
3) UI polish (pending specs from @bengolds). The current design is very raw/ugly.
=> Add/edit host view: add fields for the connection-related preferences.

app/src/main/java/org/connectbot/ConsoleActivity.java, app/src/main/java/org/connectbot/TerminalView.java, app/src/main/java/org/connectbot/service/TerminalBridge.java, app/src/main/java/org/connectbot/service/TerminalKeyListener.java, app/src/main/java/org/connectbot/util/TerminalViewPager.java, app/src/main/res/layout-large/act_console.xml, app/src/main/res/layout/act_console.xml
Fixes #232, #265, and possibly other issues.
Accidentally fixes #270. Should it? 
Extends off of #129. Big thanks to @alescdb for the initial work! (I recommend that #129 be closed now)
Long pressing on text now allows users to naturally select text as they would elsewhere in the OS. Font changes are also handled properly (see GIF).
Pre-Honeycomb devices will use the old selection method, as text selection APIs are not available for them.
GIF attached:
=> TextView in terminal for better text selection

app/src/main/java/org/connectbot/EditHostActivity.java, app/src/main/java/org/connectbot/HostEditorFragment.java, app/src/main/java/org/connectbot/HostListActivity.java, app/src/main/java/org/connectbot/bean/HostBean.java, app/src/main/java/org/connectbot/util/HostDatabase.java, app/src/main/res/menu/edit_host_activity_add_menu.xml, app/src/main/res/menu/edit_host_activity_edit_menu.xml, app/src/main/res/values/strings.xml
This PR integrates the new add/edit host view into the app and saves any host edits in the database. It's functionally complete, AFAICT.
Two remaining issues:
1) Polish UI so that it looks nice, according to mocks.
2) Remove the old HostEditorActivity.
=> Integrate EditHostActivity into the app.

app/src/main/AndroidManifest.xml, app/src/main/java/org/connectbot/TerminalView.java
Hardware acceleration was previously disabled for the entire activity,
but we only need it specifically for TerminalView.
=> Move setting of hardware acceleration to view that needs it

app/src/main/java/org/connectbot/util/TerminalTextViewOverlay.java
Fixes the issue pictured below:
=> Prevent a cursor being displayed within terminal text.

README.md
Adds a nice badge at the top of the front page, indicating build status, see how it looks at https://github.com/freshp86/connectbot.
=> Add Travis build status badge on README.md

app/build.gradle
This also fixes background issues with FABs for pre Android 4.0 devices.
Fixes #247.
=> Update from Support Library 23.0.1 to 23.1.0.

app/src/main/java/org/connectbot/ConsoleActivity.java
This avoids a race condition in ViewPager. See #301. Note that
this still looks a bit janky because the pager noticeably scrolls
away and back to the right view. A bug has been filed with the
support library team to look into a better solution.
=> Scroll to the previously selected view asynchronously.

scripts/check-lint-count.bash
The message has a better explanation (i.e., specific to the instance
it's talking about) than the summary which is fairly generic.
=> Change the lint script to use message instead of summary

.travis.yml, app/build.gradle
Since we use target API 23, we should use buildtools 23.
https://developer.android.com/tools/revisions/build-tools.html
=> Update to buildtools v23.0.1

app/src/main/java/org/connectbot/ConsoleActivity.java
Resolved #228
In TeminalManager.onUnbind() there is a call to bridge.promptHelper.setHandler(null) that is never restored.
=> Restore TerminalBridge.promptHelper.setHandler() in onServiceConnected()

app/src/main/java/org/connectbot/service/TerminalBridge.java, app/src/main/java/org/connectbot/transport/SSH.java
When multi-line output was used, this was creating a stair-step effect.
This was most noticable during host-key-has-changed warnings.
=> Avoid stair-stepping local text output

app/build.gradle, app/src/main/java/org/connectbot/HostEditorActivity.java, app/src/main/java/org/connectbot/data/HostStorage.java, app/src/main/java/org/connectbot/transport/SSH.java, app/src/main/java/org/connectbot/util/HostDatabase.java
This will allow hosts we originally saw with a certain hostkey algorithm
to continue to use those keys without warning us.
=> Support multiple known keys per host

app/src/main/java/org/connectbot/ConsoleActivity.java
If the action bar is set to auto hide, it should always be shown when
clicking the terminal. Previously, this did not happen when the virtual
keyboard was visible.
=> Make sure the action bar is always shown on click

app/src/main/java/org/connectbot/transport/SSH.java
The fact that each key type has to be handled here probably shows that
this interface is defined at the wrong level of abstraction. However,
before EC keys were not being returned as possible identities which
might have caused #378.
=> Handle EC keys in auth agent scenarios

app/src/main/java/org/connectbot/service/TerminalBridge.java
Fixe issue #391 (High CPU usage when 'Start shell session' disabled).
This patch is from Nishino Daisuke.
Original message:
https://code.google.com/archive/p/connectbot/issues/643
This patch doesn't introduce any new Android lint issues, and all checks and tests pass.
=> Avoid creating relay thread in sessionless mode

app/build.gradle
This reverts commit b2f020d8b103c4afccead82218c84596c9be677c.
We haven't updated the codebase to support vectors everywhere needed.
=> Revert "Use vector drawables"

.travis.yml, app/build.gradle, app/src/androidTest/java/org/connectbot/StartupTest.java, app/src/main/java/org/connectbot/HostEditorFragment.java
The Android instrumentation tests were disabled to check in the new host editor. Since it's been checked in, we can rewrite the tests to use the new layouts.
=> Re-enable Android instrumentation tests

app/src/main/java/org/connectbot/TerminalView.java
The accessibility buffer can be final to avoid having to do null checks
all over the place. This also avoids NPE when it's assumed to have been
created already.
This fixes #411.
=> Set accessibility buffer to final to avoid null

app/src/androidTest/java/org/connectbot/StartupTest.java, app/src/main/java/org/connectbot/ConsoleActivity.java, app/src/main/res/drawable/ic_keyboard_hide.xml, app/src/main/res/values/strings.xml
* use the button not only to show, but also to hide the keyboard
* do this more reliably, i.e. even when the focus is not on the
terminal (fixes #376)
=> Let keyboard button toggle keyboard visibility - reliably

app/src/main/java/org/connectbot/TerminalView.java
I was using [Infer](http://fbinfer.com) to check Android apps for bugs and found this in your codebase. There were 9 additional null dereference bugs but I think they may be false positives.
Please let me know if this is useful at all - I did not have the chance to run extensive testing of the changes.
Here is the full output of running `infer -- ./gradlew assemble` on the master branch before the changes in this PR (notice the `RESOURCE_LEAK` problem now resolved):
```
Found 10 issues
app/src/main/java/org/connectbot/ConsoleActivity.java:434: error: NULL_DEREFERENCE
object ConsoleActivity.actionBar last accessed on line 434 is annotated with @Nullable and is dereferenced without a null check at line 434
432.   		}
433.   		if (showActionBar) {
434. > 			actionBar.show();
435.   		}
436. …
```
=> Fixed a possible resource leak linked to a SQL cursor

app/build.gradle
This corrects intermittent issues with servers not receiving complete TELOPT  sequence causing incorrect terminal and screen size detection.
Built Telnet Response Sequences in to an ArrayList<Byte> to transpose back to a byte[] array so all response sequences are sent in a single write() instead of sending each separate byte in an individual write().
=> Telnet Protocol Handler Fixes

app/src/main/java/org/connectbot/util/EntropyView.java
Fixes #493
Just cut the string in half so that it won't crash.
At least in Chinese, Japanese and Korean, words are not separated by spaces. There are some packages that can identify words from sentences like jieba. [1] But it doesn't sound great to bring in a big dependency for this minor problem.
[1] https://github.com/huaban/jieba-analysis
=> Fix EntropyView with prompt messages without spaces

app/src/main/java/org/connectbot/util/TerminalTextViewOverlay.java
The original code [here](https://github.com/connectbot/connectbot/blob/94c1907df5a76726d3492e959c6c08778c893d76/app/src/main/java/org/connectbot/util/TerminalTextViewOverlay.java#L176) is setting the line position to int on every `scrollTo` event. So scrolling up several pixels will cause 1 line up, and scrolling down several pixels will cause nothing. This leads to #519.
In this PR, the round to int work is only done on touch up event.
There is another issue causing the scrolling no so smooth: [`refreshTextFromBuffer`](https://github.com/connectbot/connectbot/blob/94c1907df5a76726d3492e959c6c08778c893d76/app/src/main/java/org/connectbot/util/TerminalTextViewOverlay.java#L183) can run for seconds, so the view will not respond to scrolling for the first few seconds. I have no idea how to …
=> Fix the method to calculate scroll, fix #519

app/src/main/java/org/connectbot/TerminalView.java
After PixelXorXfermode was removed in API 24 and the corresponding upgrade in d372c85dd388176cc2858201f62898b6bad0e42b cursor visibility was rather a matter chance. In addition, the character under the cursor and the metaState symbols were no more visible, in any case.
Emulate the old XOR cursor by using a ColorMatrixColorFilter.
This fixes https://github.com/connectbot/connectbot/issues/533
Signed-off-by: Marc K <morckx@gmail.com>
=> Fix cursor rendering and visibility

app/src/main/java/org/connectbot/ConsoleActivity.java
this was broken by inverted logic in
36b4b5ea92bc3ede9626d73503d9139f97044cc4 -- http:// was being prepended
to urls which already contained it. But since URL scan doesn't seem to
pick up URLs without scheme anyway, this check is redundant.
fixes https://github.com/connectbot/connectbot/issues/521 & https://github.com/connectbot/connectbot/issues/517
=> do not prefix urls with http://

app/src/main/cpp/com_google_ase_Exec.cpp
Something has caused the build to break for some people and for Travis.  I suspect it was NDK update.
Regardless of the cause, the strerror function is declared in string.h, and so that header needs to be included.
=> Need to include string.h for strerror()

app/proguard.cfg
The latest SSH library uses inner classes for some of the encryption
modes, so Proguard strips them out since they're only referenced via
reflection.
This fixes #637.
=> Fix Proguard configuration

app/build.gradle
Adding BBB lets us count the number of changes since the last time ConnectBot was tagged. This will fix alpha uploading to the Play Store.
=> Generated version should roll with git

app/build.gradle
sshlib 2.2.7 was using StandardCharsets which only was supported in API
19 and later.
Fixes #654
=> Update to sshlib 2.2.8

app/src/main/java/org/connectbot/util/HostDatabase.java
Last connection time is stored in a host instance and in the db. If
not updated in the host instance before updated in the db, saveHost,
called in the connection thread, will overwrite the value in the db,
just updated from touchHost, with the old host instance value.
Fixes #594.
=> Fix last connection time race condition

Jenkinsfile
This allows the console to report what is covered and what is not.
=> Jenkinsfile: also publish Jacoco reports

.travis.yml
The new license for Oracle JDK looks like trash.
=> Travis-CI: try OpenJDK 8

app/src/main/java/de/mud/terminal/VDUBuffer.java
This change makes it such that the VDU buffer's lines are always defined
(although they might be empty).
Fixes: #710
=> Ensure that the VDU buffer's lines are never null

.travis.yml
The emulator does not start up the ADB server, so it must be called manually
before starting emulator. This appears to be a recent change.
=> Travis-CI: start adb server before emulator

.travis.yml
The interim version used emulator-headless, but now it's just chosen based on the -no-window
argument.
=> Travis-CI: keep up with emulator executable name

app/src/main/java/de/mud/terminal/vt320.java
There's an off-by-one error in the terminal emulator's handling of the ESC [ G (Cursor Horizontal Absolute) sequence.
I believe this also solves issue #702.
=> Fix an off-by-one error in ESC [ G handling

.github/workflows/export-po-files.yml
This breaks the loop that translations can cause.
=> Skip export of files if commit is empty

app/build.gradle
The less plugin are included the less future problems you will run into. 
To remove this is quite easy, because it's not used https://github.com/nobuoka/vc-gradle-android-sdk-manager#usage-version-09x
=> Remove an outdated plugin

app/build.gradle
This is required by the Google Play Store now.
=> Update targetSdkVersion to 29

app/src/main/java/org/connectbot/ConsoleActivity.java
When finish is called, remove the click listeners from the menu.  Based on event timing, these click listeners may be invoked after the activity is paused or destroyed.
This should fix issue #1015 .
@seg-ha could you test if this fixes issue #765 ?
=> Fix null pointer exception when exiting terminal.

app/build.gradle
We don't use this yet and it is causing the dex method limit to be exceeded in the next
version of espresso test framework.
=> Exclude accessibility testing

app/src/main/java/org/connectbot/TerminalView.java, app/src/main/java/org/connectbot/service/TerminalBridge.java
For certain font sizes (e.g. for 13 points), the overlay was using slightly smaller font than the terminal bridge. It appears that the overlay (i.e. TextView) is always rounding down the pixel size, whereas TerminalBridge is rounding to the closest integer.
Copy the pixel size from the bridge to the overlay to ensure perfect alignment between the two.
Remove TerminalBridge#setFontSize(), it's not used anymore. Add TerminalBridge#setFontSizePx() instead.
=> Fix text selection for certain font sizes

app/CMakeLists.txt, app/build.gradle, app/proguard-debug.cfg, app/src/main/java/org/connectbot/GeneratePubkeyActivity.java, app/src/main/java/org/connectbot/annotation/KeepForTesting.java, app/src/main/java/org/connectbot/util/EntropyView.java, app/src/main/java/org/connectbot/util/HostDatabase.java, app/src/main/java/org/connectbot/util/PubkeyDatabase.java
This is necessary to keep the classes.dex under the method limit. Newer dependencies have bloated up the tree and so we must rely on Proguard to strip everything out that is not needed.
=> Use proguard for debug configs

app/build.gradle
We can not go any farther because of a bug in 7.3.x and 7.4.x that duplicates resources when used with easylauncher.
=> Update AGP to 7.2.2

translations/build.gradle
The new version of babel 2.12.1 updated CLDR so now it does not appear to match what Launchpad is outputting. Pin babel to 2.11.0 until it can be sorted out.
=> Update translations installation

app/src/main/res/drawable/ic_launcher_monochrome.xml, app/src/main/res/mipmap-anydpi-v26/icon.xml
Adds support for themed icons (Android 13 feature).
The monochrome icon consists only of the white parts of ic_launcher_foreground (in other words, I removed the shadow and blue bar).
Seems to work fine on my device with LineageOS 20 and Trebuchet.
=> Monochrome icon

app/src/main/res/layout/inc_keyboard.xml
When scrolling emulated keys to their maximum position to the left or right on Android 12 or later, clicking the keys does not initate a response. This seems to be connected to the overscroll stretch effect introduced with Android 12 ([https://developer.android.com/about/versions/12/behavior-changes-all#overscroll)](https://developer.android.com/about/versions/12/behavior-changes-all#overscroll). 
Setting
`android:overScrollMode="never"`
for the corresponding `HorizontalScrollView` fixes that.
=> fix click failure for emulated keys when using Android > 12 

.github/workflows/ci.yml
In order to use "git describe" we need to checkout the history.
=> GitHub Actions: checkout with history on push

app/build.gradle
A change for robolectric tests accidentally included the Conscrypt library into the Google Play Store release which made the app unneccessarily large. In the Play Store version, Play Services provides the crypto library update.
=> Fix accidental size bloat

app/src/main/java/org/connectbot/transport/SSH.java, app/src/main/java/org/connectbot/transport/Telnet.java
While the "rules" may say that _ is not allowed in host and/or
domainnames, the real worl reality is that they are widely used
and not breaking anything.  So embracing the robustness principle
and accepting the world as it is rather than how it should be, allow
the use of _ in host/domainnames.
Fixes: #188
=> Allow underscores in the hostmask

.github/workflows/ci.yml
I did not notice that the tags went crazy for actual releases. This should clean it up so it is a bit easier to do releases in an automated fashion. Before the releases were getting tags like git-v1.9.10 which was not the pattern that has already been established.
=> Fix up release names and tags

.github/workflows/ci.yml
Keep native debug symbols from release builds for possible debugging later.
=> Upload native debug symbols during build

.github/workflows/ci.yml
`macos-latest` uses macOS 14 now which appears to have an issue starting the Android emulator.
See https://github.com/ReactiveCircus/android-emulator-runner/issues/392#issuecomment-2106167725
=> Pin GitHub Actions to use macOS 13

app/locale/fortune/tk.po, app/src/main/res/values-tk/strings.xml, translations/build.gradle
Rosetta was incorrectly saying that Turkmen only had one plural form, but it should have two.
=> Add Turkmen translations

app/src/main/AndroidManifest.xml, app/src/main/java/org/connectbot/HostListActivity.java, app/src/main/res/values/strings.xml
Add Android 13 POST_NOTIFICATIONS runtime permission
Request the permission after clicking on a Host and before starting the Console (only on Android 13+ devices).
Resolves [1352](https://github.com/connectbot/connectbot/issues/1352)
=> Fix Persistent notification no longer working

app/src/main/res/mipmap-anydpi-v26/icon_round.xml
Previously, the monochrome version of the icon wasn't referenced correctly from within `icon_round.xml` leading to the themed icon not working correctly in some launchers.
=> Fix themed app icon

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/connectbot/service/ConnectionNotifier.java, app/src/main/java/org/connectbot/util/PreferenceConstants.java
Remote messaging seems to be close to what we are doing with long-lived TCP connections sending messages to the remote server and receiving them back.
Make sure that the initial foreground notification is silent when we first start up since the default seems to have changed.
=> Add startForeground service type
