.travis.yml, app/app.iml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/connectbot/service/ConnectionNotifier.java
Switch to using NotificationCompat.Builder. This will allow for
the creation of a "disconnect all" button in the notification
(see #93).
=> Add the v4 support library and update the notification API.

app/src/main/java/org/connectbot/ConsoleActivity.java
I'm not sure this fixes all the scaling problems we talked about, but it does seem to have a positive impact on scrolling with my Nexus 9.
=> Use scaled touch slop for determining the scroll x-tolerance.

app/src/main/res/values-it/strings.xml
This was "username" and now is the same values as hostpref_nickname_title
=> Fix italian translation of prompt_nickname.

app/src/main/java/org/connectbot/service/TerminalKeyListener.java
=> Make ctrl-shift-v paste.

app/src/main/java/org/connectbot/ConsoleActivity.java, app/src/main/res/layout/act_console.xml
This simplifies the code for creating terminals, removes lots of code,
and totally eliminates the need for swipe handling.
From the UI side, the swipe now sticks to the user's finger and looks
much nicer. It will also make adding tabs much simpler.
=> ConsoleActivity: Switch from ViewFlipper to ViewPager.

app/src/main/java/org/connectbot/ConsoleActivity.java
Fixes some errors that happens when you start forced in landscape mode.
=> Check for null on TerminalManager

app/src/main/java/org/connectbot/service/TerminalBridge.java
This will resolve a crash when disconnecting hosts with "close on disconnect" set to true. See https://github.com/connectbot/connectbot/issues/135.
=> Handle immediate disconnection listeners on the UI thread

app/src/main/java/org/connectbot/ConsoleActivity.java, app/src/main/res/layout-large/act_console.xml, app/src/main/res/layout/act_console.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
Multiple conflicts in the XML files caused this to be kind of hairy.
=> Merge hscroll change from @alescdb 

app/src/main/jni/com_google_ase_Exec.cpp
grantpt doesn't do anything on Android since it uses devpts.
=> Remove reference to grantpt

app/src/main/java/org/connectbot/ConsoleActivity.java
=> Reset virtual keyboard auto-hide timer on hscroll

app/build.gradle
23.0.1. is the new version automatically downloaded in Android Studio.
=> Bump the support library version from 23.0.0 to 23.0.1.

.linthub.yml, app/src/main/java/org/connectbot/HostListActivity.java
=> Go back to old context-using setTextAppearance call

app/src/main/AndroidManifest.xml, app/src/main/java/org/connectbot/ColorsActivity.java, app/src/main/java/org/connectbot/EulaActivity.java, app/src/main/java/org/connectbot/HelpActivity.java, app/src/main/java/org/connectbot/HelpTopicActivity.java, app/src/main/java/org/connectbot/HostListActivity.java, app/src/main/java/org/connectbot/PortForwardListActivity.java, app/src/main/java/org/connectbot/PubkeyListActivity.java, app/src/main/res/values/strings.xml
=> Add parent activities for all activities

app/src/main/AndroidManifest.xml, app/src/main/res/values-v11/styles.xml, app/src/main/res/values-v21/styles.xml, app/src/main/res/values/styles.xml
=> Add Material theme palette

app/src/main/java/org/connectbot/bean/HostBean.java, app/src/main/java/org/connectbot/util/HostDatabase.java
=> Fix the known host prompting repeatedly

app/src/main/java/org/connectbot/transport/Local.java
=> Kill shell process after exiting local transport

app/src/main/java/org/connectbot/HostListActivity.java
This partially reverts commit fc419491da8693446a98abf9461c00ecf21daa4b.
Fixes problem with merge of #206
=> Revert "Extend AppCompatActivity instead of Activity."

app/src/main/res/values/strings.xml
=> Fix empty host list blurb. (in English only)

app/src/main/java/org/connectbot/HostEditorActivity.java
=> Fix missing summaries for SwitchPreferences in host editing list.

app/src/main/java/org/connectbot/GeneratePubkeyActivity.java
=> Give color to action button in GeneratePubkeyActivity.

app/src/main/AndroidManifest.xml
=> Make HostListActivity use intended title 'Hosts'.

app/src/main/AndroidManifest.xml
=> Fix app name in launcher being 'Hosts'

app/src/main/res/values/colors.xml
Uses the "Light blue + Light blue (slightly lightened)" color combo from #256
=> Change app color scheme to light blue

app/src/main/AndroidManifest.xml, app/src/main/java/org/connectbot/HostEditorFragment.java, app/src/main/java/org/connectbot/bean/HostBean.java, app/src/main/res/layout/fragment_host_editor.xml
Note that the XML had 2-space tabs for some reason, so I fixed that as well. That's why it shows up as a bigger XML change than it actually was.
=> Add host display properties (e.g., color, font size) to add/edit host view.

app/src/main/java/de/mud/terminal/VDUBuffer.java, app/src/main/java/de/mud/terminal/vt320.java
=> Fix bad math in moving the cursor when the window size changes.

app/src/main/java/org/connectbot/PortForwardListActivity.java
=> Fixed error when not filling in all fields of port forward creation dialog

app/src/main/AndroidManifest.xml, app/src/main/java/org/connectbot/HostListActivity.java
Actually fixes #244. 
PR #245 did not actually fix this issue.
See http://stackoverflow.com/a/23155350 for more info.
=> Display correct app name in launcher.

app/src/main/java/org/connectbot/TerminalView.java, app/src/main/java/org/connectbot/util/PreferenceConstants.java, app/src/main/res/values/strings.xml, app/src/main/res/xml-v14/preferences.xml, app/src/main/res/xml/preferences.xml
=> Make the pg up/down gesture a preference which is disabled by default.

app/src/main/java/org/connectbot/ConsoleActivity.java
=> Show ActionBar when TerminalView is touched.

app/src/main/java/org/connectbot/ConsoleActivity.java, app/src/main/java/org/connectbot/TerminalView.java
=> Fix paste button being permanently disabled when clipboard was previously empty.

app/src/main/java/org/connectbot/ConsoleActivity.java, app/src/main/res/layout-large/act_console.xml, app/src/main/res/layout/act_console.xml, app/src/main/res/layout/act_generatepubkey.xml, app/src/main/res/layout/dia_changepassword.xml, app/src/main/res/layout/dia_password.xml
Fixes #295.
I'd prefer this not be merged until @alescdb weighs in on it.
=> Fix paste button being permanently disabled because SSH session was not yet open.

app/src/main/java/org/connectbot/HostEditorFragment.java, app/src/main/java/org/connectbot/bean/HostBean.java, app/src/main/res/layout/fragment_host_editor.xml, app/src/main/res/values-v11/styles.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/styles.xml
This finalizes the add/edit host view, except for these:
1) Introduce "do you want to discard edits" dialog when user clicks back.
2) Include the correct icons instead of the ConnectBot icon for every icon.
3) Grey out the "save/edit" icon when the host is invalid.
=> Polish UI for add/edit host.

app/src/main/res/layout/item_host.xml, app/src/main/res/layout/item_portforward.xml, app/src/main/res/layout/item_pubkey.xml
Fixes #264 and is an extension of #300 
Pubkey list before:
Pubkey list after: 
Port forward list after:
=> Style port forward and pubkey list like the host list.

app/src/main/java/org/connectbot/HostEditorFragment.java, app/src/main/res/layout/fragment_host_editor.xml
=> Don't display a nickname field when protocol is 'local.'

app/src/main/java/org/connectbot/service/TerminalManager.java
=> Call MediaPlayer.seekTo() before MediaPlayer.start()

app/src/main/java/org/connectbot/HostListActivity.java, app/src/main/res/values/strings.xml
Fix https://github.com/connectbot/connectbot/issues/176
=> Add DisconnectAll to HostActivity's Options.

app/src/main/java/org/connectbot/util/HostDatabase.java
The host keys were not being inserted because it was using the old
update code, so fix that up and make sure that known host entries are
deleted when hosts are deleted.
This fixes issue #380.
=> Make sure new known hosts are inserted and deleted

.travis.yml, app/build.gradle, app/src/androidTest/java/org/connectbot/StartupTest.java, app/src/main/java/org/connectbot/HostEditorFragment.java, app/src/main/java/org/connectbot/HostListActivity.java, app/src/main/java/org/connectbot/views/CheckableMenuItem.java, app/src/main/res/layout/act_hostlist.xml, app/src/main/res/layout/fragment_host_editor.xml, app/src/main/res/layout/view_checkablemenuitem.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/strings.xml, config/jacoco.gradle, config/quality.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
This improves the accessibility of the Add Host / Edit Host functionality.
=> Edit host accessibility

app/build.gradle
=> Add ribbon identifying debug version

app/src/main/java/org/connectbot/service/BackupAgent.java, app/src/main/java/org/connectbot/util/PreferenceConstants.java, app/src/main/res/values/strings.xml, app/src/main/res/xml-v14/preferences.xml, app/src/main/res/xml/preferences.xml
=> Add preference for backing up pubkeys

app/app.iml, app/build.gradle, app/src/main/java/org/connectbot/views/CheckableMenuItem.java
Some times we were being passed in 0x7fffffff instead of the HOST_ID
(-1) that we were expecting.
This fixes #466.
=> Ignore invalid virtualViewId

.travis.yml, app/app.iml, app/build.gradle, app/src/androidTest/java/org/connectbot/StartupTest.java, app/src/main/java/org/connectbot/HostEditorFragment.java, app/src/main/java/org/connectbot/HostListActivity.java, app/src/main/java/org/connectbot/SettingsActivity.java, app/src/main/java/org/connectbot/service/TerminalManager.java, app/src/main/java/org/connectbot/util/TerminalTextViewOverlay.java
This will upgrade the crypto stack if it's available.
=> Add support for Google Play Services ProviderInstaller

app/src/main/java/org/connectbot/TerminalView.java, app/src/main/java/org/connectbot/service/TerminalBridge.java, app/src/main/java/org/connectbot/util/TerminalTextViewOverlay.java
This should fix #377 and also a TextView synchronization problem I noticed while working on that.
=> Fix some TerminalTextViewOverlay bugs

.travis.yml
This apparently still has some bugs, but it seems like we have no choice!
=> Use the new avdmanager

app/src/main/AndroidManifest.xml, app/src/main/res/layout-large/act_console.xml, app/src/main/res/layout/act_console.xml, app/src/main/res/layout/act_generatepubkey.xml, app/src/main/res/layout/act_help.xml, app/src/main/res/layout/dia_changepassword.xml, app/src/main/res/layout/dia_gatherentropy.xml, app/src/main/res/layout/dia_portforward.xml, app/src/main/res/layout/dia_resize.xml, app/src/main/res/layout/view_checkablemenuitem.xml, app/src/main/res/values-v11/styles.xml, app/src/main/res/values/styles.xml
Most views look fine in RTL. Enable it in the manifest.
=> Indicate support for RTL

app/src/main/java/org/connectbot/service/TerminalKeyListener.java
=> Translate ctrl plus @ into ctrl-@

app/src/main/java/de/mud/terminal/VDUBuffer.java, app/src/main/java/de/mud/terminal/vt320.java, app/src/main/java/org/connectbot/TerminalView.java, app/src/main/java/org/connectbot/service/TerminalBridge.java
Handle true-color control codes, extending attributes to contain the
extra bits, and display the desired colors.
Fixes issue #457
=> Add true-color (24-bit) support

.travis.yml, app/app.iml, app/build.gradle, build.gradle, connectbot.iml, gradle.properties, gradle/wrapper/gradle-wrapper.properties
Use Gradle 4.4 and Android Gradle Plugin 3.1.2
=> Update build tools

app/src/main/java/org/connectbot/service/TerminalBridge.java
* take into to account that the user can also change the font scale
(under system-settings -> display -> font size)
* take into account that density and font scale can be changed while the app is
running
This should fix #532 in cases where font scale is not 1.0.
=> Respect font scale and changed system settings in font size calculation

app/build.gradle
This does not seem to do much currently for our code.
=> Enabled resource shrinking

app/build.gradle, app/src/main/java/org/connectbot/transport/SSH.java
This enables Encrypt-Then-MAC modes of encryption for peers that support it.
=> Update to sshlib 2.2.6

app/src/main/java/org/connectbot/util/TerminalTextViewOverlay.java
=> Fix off-by-one when copying text from buffer

app/build.gradle, app/locale/fortune/fortune-ar.po, app/src/main/res/values-ar/strings.xml
Some prerequisites I need to make releases a big easier.
=> Set up for release v1.9.3

.idea/runConfigurations/All_tests.xml, .travis.yml, app/app.iml, app/build.gradle, app/proguard.cfg, build.gradle, gradle.properties
45 minutes is the limit and we're dangerously close to that.
=> Try to improve the Travis build times

app/src/main/res/layout/act_eula.xml
Removed in commit 7427feaa198f0bfe04c0f7fadfbc69d4b1a7b299 from sshlib.
=> JSOCKS is not used anymore

Jenkinsfile, app/build.gradle
This was looking in the wrong directory for coverage information
which made everything look like it was 100% covered.
=> Jenkinsfile: fix coverage

app/src/main/java/org/connectbot/service/ConnectionNotifier.java
This isn't needed anymore since we do not run on pre-Eclair devices.
=> ConnectionNotifier: remove compat code

README.md
=> README.md:correct spelling (translations)

.travis.yml
SDK manager was stalling asking if we wanted to accept the license.
=> travis-ci: accept all licenses for sdkmanager

.travis.yml
Reverts connectbot/connectbot#699
=> Revert "Travis-CI: try OpenJDK 8"

app/locale/fortune/fortune.pot, app/locale/fortune/ru.po, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/strings.xml
=> Export translations for the Russian update

app/build.gradle, app/src/main/java/org/connectbot/GeneratePubkeyActivity.java, app/src/main/java/org/connectbot/transport/SSH.java, app/src/main/java/org/connectbot/util/PubkeyUtils.java
Renamed EdDSA classes to Ed25519 to retain backward compatibility.
Fixes #811
=> Upgrade to sshlib 2.2.14

app/src/main/java/org/connectbot/TerminalView.java
fix for https://github.com/connectbot/connectbot/issues/842
=> Turn off suggestions

app/src/androidTest/java/org/connectbot/PubkeyListActivityTest.java, app/src/androidTest/java/org/connectbot/ScrollToAction.java
fix travis test error
```
org.connectbot.PubkeyListActivityTest > generateRSAKey[test(AVD) - 9] FAILED 
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id is <org.connectbot.debug:id/list>
```
=> fix test error

app/build.gradle, app/src/main/java/org/connectbot/AppCompatListActivity.java, app/src/main/java/org/connectbot/ConsoleActivity.java, app/src/main/java/org/connectbot/HostEditorFragment.java, app/src/main/java/org/connectbot/TerminalView.java, app/src/main/java/org/connectbot/bean/PubkeyBean.java, app/src/main/java/org/connectbot/util/HostDatabase.java, app/src/main/java/org/connectbot/util/UberColorPickerDialog.java
Additional it removes a lot of them
=> Automatic code clean up

app/build.gradle, build.gradle, config/quality.gradle, settings.gradle, spotless.gradle, translations/build.gradle
With it you can do 
and spotless will not find an "error" in `*.gradle` files
=> Harmonize spotless with Android Studio formatter

.github/workflows/ci.yml
=> Proposal to reduce CI builds, my pull request builds twice

app/build.gradle
Some dependencies require 31 now.
=> Set compileSdkVersion to 31

app/src/main/java/org/connectbot/ConsoleActivity.java, app/src/main/java/org/connectbot/service/TerminalManager.java
e.g 
and some more lint warnings
=> Fix lint warnings

.github/workflows/ci.yml, app/build.gradle, app/proguard-tests.cfg, app/proguard.cfg, app/src/main/AndroidManifest.xml, app/src/main/java/org/connectbot/ConsoleActivity.java, app/src/main/java/org/connectbot/EditHostActivity.java, app/src/main/java/org/connectbot/PubkeyListActivity.java, app/src/main/java/org/connectbot/util/VolumePreference.java, gradle.properties, gradle/wrapper/gradle-wrapper.properties, settings.gradle, translations/build.gradle
=> Update the Android SDK to newest version

.github/workflows/ci.yml
Simulate what Jenkins used to do.
=> Upload to releases every build

.github/workflows/ci.yml
This will emulate what was done by Jenkins before.
=> GitHub Actions: Explicitly set tag name

.github/workflows/ci.yml
This calls a remote signing server to sign the releases.
=> Sign releases after being uploaded

.github/workflows/ci.yml
The previous step containing the tag was missing.
=> Fix call to signing service

.github/workflows/ci.yml
Make the code a bit more easy to follow using JSON notation.
=> GitHub Actions: use fromJSON expression

.github/workflows/ci.yml
Other webhook action seems to be abandoned.
=> Use different codesigner trigger

app/build.gradle
Mitigation for the Terrapin attack.
=> Update to sshlib 2.2.22

.github/workflows/translations-import.yml
The import tool does not work correctly with Turkmen currently.
=> Exclude Turkmen from translations import

.github/workflows/ci.yml, .github/workflows/gradle-wrapper-validation.yml, .github/workflows/translations-import.yml
Update the Gradle actions in the GitHub workflows.
=> Gradle wrapper validation
